openapi: 3.0.0
info:
  title: pathRef
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/pet':
    $ref: ./petstore.yaml#/paths/~1pet
  '/pet/{petId}':
    $ref: ./petstore.yaml#/paths/~1pet~1{petId}
  '/store/order/{orderId}':
    $ref: ./petstore.yaml#/paths/~1store~1order~1{orderId}
